spring:
  datasource:
    url: jdbc:h2:file:/home/vighanesh/session_demo
    driver-class-name: org.h2.Driver
    username: sa
    password: SecretPassword

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

server:
  servlet:
    session:
      timeout: 60s